language: go
go:
  - master
install:
  - go build -v ./...

script:
  - echo "" > coverage.txt
  - "for d in $(go list ./... | grep -v vendor); do \n
        COV=$(go test -race  -coverprofile=profile.out -covermode=atomic $d | sed  's/[^0-9]*\([0-9]*\.[0-9]\).*/\1/') | if [[ ( $COV -lt 70 ) ]]; then 
          echo insufficient tests; 
          exit 1 \n
        fi
        go test -race -coverprofile=profile.out -covermode=atomic $d \n
        if [ $? -gt 0 ]; then \n
          exit 1 \n
        elif [ -f profile.out ]; then \n
          cat profile.out >> coverage.txt \n
          rm profile.out \n
      fi \n
    done"

after_success:
  - bash <(curl -s https://codecov.io/bash)
